data:
  train_ann: multimodal-data/DINO_GAI20II/train_annotations.csv
  train_dir: multimodal-data/DINO_GAI20II/images/train
  val_ann: multimodal-data/DINO_GAI20II/val_annotations.csv
  val_dir: multimodal-data/DINO_GAI20II/images/val
  batch_size: 4
  num_workers: 8

model:
  config_path: "groundingdino/config/GroundingDINO_SwinT_OGC.py"
  weights_path: "weights/groundingdino_swint_ogc.pth"

training:
  num_epochs: 20
  learning_rate: 1e-3
  save_dir: "weights"
  save_frequency: 5
  warmup_epochs: 5
  use_lora: true
  lora_rank: :32
  visualization_frequency: 2
