data:
  train_ann: multimodal-data/DINO_GAI20II/train_annotations.csv
  train_dir: multimodal-data/DINO_GAI20II/images/train
  val_ann: multimodal-data/DINO_GAI20II/val_annotations.csv
  val_dir: multimodal-data/DINO_GAI20II/images/val
  batch_size: 4
  num_workers: 8

model:
  config_path: groundingdino/config/GroundingDINO_SwinT_OGC.py
  lora_weights: weights/20250610_1311/checkpoint_epoch_2.pth
  weights_path: weights/groundingdino_swint_ogc.pth

training:
  learning_rate: 0.0001
  num_epochs: 200
  save_dir: weights
  save_frequency: 5
  use_lora: True
  lora_rank: 32
  visualization_frequency: 5
  warmup_epochs: 5
